<div class="">
    <ul class="breadcrumb">
        <li><i class="fa fa-home fa-lg"></i> <a href="./"><?= $this->translate('Home') ?></a></li>
    </ul>

    <div class="content">
	<div class="jumbotron well-lg" style="border-left: 5px solid #178EC7; padding-top: 40px; padding-bottom: 40px;"><h1 style="font-weight:bold;"><?= $this->translate('Welcome to Knowledgeroot') ?></h1></div>
    </div>
</div><!--/span-->
