<script src="system/javascript/bootstrap-tabs.js" type="text/javascript"></script>
<div class="page-header">
    <h2>
	<?php
	    if($this->action == 'new')
		echo "Create Content";
	    else
		echo "Edit Content";
	?>
    </h2>
</div>
<form class="form-horizontal" method="post">
    <div class="tabbable">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#tab-content">Content</a></li>
	    <li><a data-toggle="tab" href="#tab-position">Position</a></li>
	    <li><a data-toggle="tab" href="#tab-permission">Permissions</a></li>
	    <li><a data-toggle="tab" href="#tab-info">Information</a></li>
	    <li><a data-toggle="tab" href="#tab-history">History</a></li>
	</ul>
	<div class="tab-content">
	    <div class="tab-pane active" id="tab-content">
		<fieldset>
		    <div class="control-group">
			<label class="control-label" for="content-title">Titel</label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="content-title" name="content_title" value="<?= $this->title; ?>" size="255">
			    <p class="help-block">
				Title of content.
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="content-editor">Content</label>
			<div class="controls">
			    <?php
			    echo $this->editor;
			    ?>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="content-tags">Tags</label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="content-tags" name="content-tags" value="<?= $this->tags; ?>">
			    <p class="help-block">
				Comma separated words.
			    </p>
			</div>
		    </div>
		</fieldset>
	    </div>
	    <div class="tab-pane" id="tab-position">
		    <div class="control-group">
			<label class="control-label" for="content-page">Seite</label>
			<div class="controls">
			    <input type="text" class="input-xlarge span2" id="content-page" name="content_page" value="<?= $this->page; ?>" size="255">
			    <p class="help-block">
				Page
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="position">Position</label>
			<div class="controls">
			    <select name="position" id="position">
				<?php
				if(is_array($this->positions)) {
				    foreach ($this->positions as $position) {
					echo '<option value="' . $position['key'] . '"' . (($position['default']) ? ' selected="selected"' : '') . '>&larr; ' . $position['title'] . '</option>';
				    }
				}
				?>
			    </select>
			    <p class="help-block">
				Define position of content on page.
			    </p>
			</div>
		    </div>
	    </div>
	    <div class="tab-pane" id="tab-permission">
		<?php
		echo $this->partial("rights.phtml");
		?>
	    </div>
	    <div class="tab-pane" id="tab-info">
		    <div class="control-group">
			<label class="control-label" for="content-title">Created By</label>
			<div class="controls">
			    <span class="input-xlarge uneditable-input">admin</span>
			    <p class="help-block">
				username
			    </p>
			</div>
		    </div>
		    <div class="control-group">
			<label class="control-label" for="content-title">Created at</label>
			<div class="controls">
			    <span class="input-xlarge uneditable-input">20120606</span>
			    <p class="help-block">
				creation date
			    </p>
			</div>
		    </div>
	    </div>
	    <div class="tab-pane" id="tab-history">
	    </div>
	</div>
    </div>
    <div class="form-actions">
	<button class="btn btn-primary" type="submit" name="button" value="save">Save</button>&nbsp;
	<button class="btn" type="submit" name="button" value="save_and_close">Save and Close</button>&nbsp;
	<button class="btn btn-danger" type="submit" name="button" value="close">Close</button>&nbsp;
    </div>
</form>
