<!-- anchor --><a name="<?php echo $this->id; ?>"></a>
<div class="accordion" id="accordion<?php echo $this->id; ?>"><!-- start accordian -->
    <div class="accordion-group">
	<div class="accordion-heading" style="background-color: #F6F6F6;">

	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion<?php echo $this->id; ?>" href="#collapse<?php echo $this->id; ?>">
		<?php echo $this->title; ?>
	    </a>

	</div>
	<div id="collapse<?php echo $this->id; ?>" class="accordion-body collapse<?php if ($this->open) echo ' in'; ?>">

	    <div class="accordion-inner">
		<div class="btn-toolbar">
		    <?php echo $this->contentNavi; ?>
		    <?php echo $this->contentNavi2; ?>
		</div>
		<br>
		<?php echo $this->content; ?>
	    </div>
	    <div class="content_statusbar"><?php echo $this->statusBar; ?></div>
	</div>
    </div>
</div><!-- end accordian -->