<div class="page-header">
    <h2>Groups</h2>
</div>
<div class="form-actions">
    <a class="btn btn-primary" href="index.php?action=addgroup">New Group</a>
</div>
<table class="table table-striped table-bordered table-condensed">
    <thead>
	<tr>
	    <th>#</th>
	    <th>name</th>
	    <th>description</th>
	    <th>active</th>
	    <th>action</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach($this->groups as $value) { ?>
	<tr>
	    <td><?php echo $value['id']; ?></td>
	    <td><?php echo $value['name']; ?></td>
	    <td></td>
	    <td></td>
	    <td>
		<a class="btn" href="index.php?action=editgroup&gid=<?php echo $value['id']; ?>">edit</a>
		<a class="btn btn-danger" onclick="if(!confirm('Do you really want to delete this group?')) return false;" href="index.php?action=delgroup&gid=<?php echo $value['id']; ?>">delete</a>
	    </td>
	</tr>
	<?php } ?>
    </tbody>
</table>