
<div class="page-header">
    <h2>Login</h2>
</div>
<form class="form-horizontal" action="index.php" method="post" name="loginformular">
    <input type="hidden" name="<?php session_name(); ?>" value="<?php session_id(); ?>" />
    <input type="hidden" name="login" value="login" />

    <div class="control-group">
	<label class="control-label" for="user">User</label>
	<div class="controls">
	    <input type="text" class="input-xlarge" id="user" name="user">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="password">Password</label>
	<div class="controls">
	    <input type="password" class="input-xlarge" id="password" name="password">
	</div>
    </div>

    <div class="form-actions">
	<input class="btn btn-primary" type="submit" name="loginbutton" value="login" />
    </div>
</form>

<script type="text/javascript">
    <!--
    document.loginformular.user.focus();
    //-->
</script>