<!-- -->
<script>
    var memberStore_<?= $this->name ?> = <?php echo ((count($this->permissions) > 0) ? json_encode($this->permissions) : '{}'); ?>;
    var roleStore_<?= $this->name ?> = <?= json_encode($this->roles) ?>;
</script>

<!-- main member panel -->
<div class="member-panel" data-panel-name="<?= $this->name ?>">
    <button class="btn" data-toggle="modal" href="#memberPanelRoles_<?= $this->name ?>">add Role</button>
    <button type="button" class="btn" data-panel-event="mem_removeUser">remove selected Role</button>
    <div class="row-fluid">
	<div class="span6">
	    <h5>Gruppen- order Benutzernamen:</h5>
	    <div class="member-panel-roles">
		<ul>
		    <?php foreach ($this->permissions as $key => $value) { ?>
    		    <li><a data-panel-name="<?= $this->name ?>" data-panel-userid="<?= $key ?>" href="javascript:;"><?= $value['name'] ?> (<?= $key[0] ?>)</a></li>
		    <?php } ?>
		</ul>
	    </div>
	</div>
    </div>
    <input type="hidden" id="inputAcl<?= $this->name ?>" name="acl" value="" />
    <script>
	$(window).load(function() {
	    mem_updateAclField('<?= $this->name ?>');
	});
    </script>
</div>

<!-- modal box with available roles -->
<div id="memberPanelRoles_<?= $this->name ?>" data-panel-name="<?= $this->name ?>" class="memberPanelRoles modal hide fade" tabindex="-1" role="dialog" aria-labelledby="memberPanelRoles_<?= $this->name ?>_Label" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    <h3 id="">Roles</h3>
	</div>
	<div class="modal-body">
	    <h5>Select roles to add:</h5>
	    <select multiple="multiple">
		<?php foreach($this->roles as $key => $value) { ?>
		<option value="<?= $key ?>"><?= $value ?></option>
		<?php } ?>
	    </select>
	</div>
	<div class="modal-footer">
	    <button class="btn btn-primary" data-panel-event="mem_addUser" type="button">Add</button>
	    <button class="btn" data-dismiss="modal">Cancel</button>
	</div>
</div>