<!-- -->
<script>
    var permissionStore_<?= $this->name ?> = <?php echo ((count($this->permissions) > 0) ? json_encode($this->permissions) : '{}'); ?>;
    var roleStore_<?= $this->name ?> = <?= json_encode($this->roles) ?>;
    var actionStore_<?= $this->name ?> = <?= json_encode($this->actions) ?>;
</script>

<!-- main permission panel -->
<div class="permission-panel" data-panel-name="<?= $this->name ?>">
    <button class="btn" data-toggle="modal" href="#permissionPanelRoles_<?= $this->name ?>">add Role</button>
    <button class="btn" data-panel-event="removeUser">remove selected Role</button>
    <div class="row-fluid">
	<div class="span6">
	    <h5>Gruppen- order Benutzernamen:</h5>
	    <div class="permission-panel-roles">
		<ul>
		    <?php foreach ($this->permissions as $key => $value) { ?>
    		    <li><a data-panel-name="<?= $this->name ?>" data-panel-userid="<?= $key ?>" href="javascript:;"><?= $value['name'] ?> (<?= $key[0] ?>)</a></li>
		    <?php } ?>
		    <!-- <li><a class="active" href="javascript:;">test1</a></li> -->
		</ul>
	    </div>
	</div>

	<div class="span6">
	    <h5>Berechtigungen:</h5>
	    <div class="permission-panel-rights well well-small" data-panel-name="<?= $this->name ?>" style="display:none;">
		<?php
		foreach ($this->actions as $value) {
		    ?>
    		<div class="action" data-panel-action-name="<?= $value ?>">
    		    <span class="action-name"><?= $value ?>:</span>
    		    <div class="btn-group" data-toggle="buttons-radio">
    			<button type="button" class="btn btn-small btn-success" data-panel-name="<?= $this->name ?>" data-panel-action-name="<?= $value ?>" data-panel-action-right="allow">allow</button>
    			<button type="button" class="btn btn-small btn-danger" data-panel-name="<?= $this->name ?>" data-panel-action-name="<?= $value ?>" data-panel-action-right="deny">deny</button>
    		    </div>
    		</div>
		<?php } ?>
	    </div>
	</div>
    </div>
    <?php if($this->showSaveButton) { ?>
    <div class="row-fluid">
	<div class="pull-right">
	    <button class="btn btn-primary permission-panel-save-button" data-panel-name="<?= $this->name ?>" data-panel-save-url="./permissions/save">save</button>
	</div>
    </div>
    <?php } ?>
    <?php if($this->addAclOnFormSubmit) { ?>
    <input type="hidden" id="inputAcl<?= $this->name ?>" name="acl" value="" />
    <?php } ?>
</div>

<!-- modal box with available roles -->
<div id="permissionPanelRoles_<?= $this->name ?>" data-panel-name="<?= $this->name ?>" class="permissionPanelRoles modal hide fade" tabindex="-1" role="dialog" aria-labelledby="permissionPanelRoles_<?= $this->name ?>_Label" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    <h3 id="">Roles</h3>
	</div>
	<div class="modal-body">
	    <h5>Select roles to add:</h5>
	    <select multiple="multiple">
		<?php foreach($this->roles as $key => $value) { ?>
		<option value="<?= $key ?>"><?= $value ?></option>
		<?php } ?>
	    </select>
	</div>
	<div class="modal-footer">
	    <button class="btn btn-primary" data-panel-event="addUser" type="button">Add</button>
	    <button class="btn" data-dismiss="modal">Cancel</button>
	</div>
</div>