<div class="row">
    <div class="span6">
	<fieldset>
	    <div class="control-group">
		<label class="control-label" for="content-title">Benutzer:</label>
		<div class="controls">
		    <select>
			<option value="">admin</option>
			<option value="">xxx</option>
			<option value="">yyy</option>
		    </select>
		</div>
	    </div>
	</fieldset>
    </div>
    <div class="span6">
	<fieldset>
	    <div class="control-group">
		<label class="control-label" for="content-title">Benutzerrechte:</label>
		<div class="controls">
		    <select>
			<option value="">Lesen+Schreiben</option>
			<option value="">Lesen</option>
			<option value="">keine</option>
		    </select>
		</div>
	    </div>
	</fieldset>
    </div>
</div>

<div class="row">
    <div class="span6">
	<fieldset>
	    <div class="control-group">
		<label class="control-label" for="content-title">Gruppe:</label>
		<div class="controls">
		    <select>
			<option value="">admin</option>
			<option value="">xxx</option>
			<option value="">yyy</option>
		    </select>
		</div>
	    </div>
	</fieldset>
    </div>
    <div class="span6">
	<fieldset class="control-group">
	    <div class="control-group">
		<label class="control-label" for="content-title">Gruppenrechte:</label>
		<div class="controls">
		    <select>
			<option value="">Lesen+Schreiben</option>
			<option value="">Lesen</option>
			<option value="">keine</option>
		    </select>
		</div>
	    </div>
	</fieldset>
    </div>
</div>


<div class="row">
    <div class="span6">&nbsp;
    </div>
    <div class="span6">
	<fieldset>
	    <div class="control-group">
		<label class="control-label" for="content-title">Rechte sonstiger:</label>
		<div class="controls">
		    <select>
			<option value="">Lesen+Schreiben</option>
			<option value="">Lesen</option>
			<option value="">keine</option>
		    </select>
		</div>
	    </div>
	</fieldset>
    </div>
</div>




<div class="row">
    <div class="span6">
	<fieldset>
	    <div class="control-group">
		<label class="control-label" for="content-title">Benutzer:</label>
		<div class="controls">
		    <select>
			<option value="">admin</option>
			<option value="">xxx</option>
			<option value="">yyy</option>
		    </select>
		</div>
	    </div>
	</fieldset>
    </div>
    <div class="span6">
	<fieldset>
	    <div class="control-group">
		<label class="control-label" for="content-title">Benutzerrechte:</label>
		<div class="controls">
		    <select>
			<option value="">Lesen+Schreiben</option>
			<option value="">Lesen</option>
			<option value="">keine</option>
		    </select>
		    <button class="btn btn-small btn-danger"><i class="icon-remove"></i></button>
		</div>
	    </div>
	</fieldset>
    </div>
</div>

<div class="row">
    <div class="span6">
	<fieldset>
	    <div class="control-group">
		<label class="control-label" for="content-title">Gruppe:</label>
		<div class="controls">
		    <select>
			<option value="">admin</option>
			<option value="">xxx</option>
			<option value="">yyy</option>
		    </select>
		</div>
	    </div>
	</fieldset>
    </div>
    <div class="span6">
	<fieldset class="control-group">
	    <div class="control-group">
		<label class="control-label" for="content-title">Gruppenrechte:</label>
		<div class="controls">
		    <select>
			<option value="">Lesen+Schreiben</option>
			<option value="">Lesen</option>
			<option value="">keine</option>
		    </select>
		    <button class="btn btn-small btn-danger"><i class="icon-remove"></i></button>
		</div>
	    </div>
	</fieldset>
    </div>
</div>


<div style="text-align:center">
	<div style="margin:auto;">
	    <a class="btn" href="#">Benutzerrechte hinzufügen</a>
	    <a class="btn" href="#">Gruppenrechte hinzufügen</a>
	</div>
</div>
