<div class="page-header">
    <h2>
	<?php
	if ($this->action == 'new')
	    echo "Create User";
	else
	    echo "Edit User";
	?>
    </h2>
</div>
<form class="form-horizontal" method="post">
    <div class="tabbable">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#tab-user">User</a></li>
	    <li><a data-toggle="tab" href="#tab-member">Member Of</a></li>
	    <li><a data-toggle="tab" href="#tab-permission">Permissions</a></li>
	</ul>
	<div class="tab-content">
	    <div class="tab-pane active" id="tab-user">
		<div class="control-group">
		    <label class="control-label" for="login">Login</label>
		    <div class="controls">
			<input type="text" class="input-xlarge" id="login" name="login" value="<?php echo $this->login; ?>">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="password">Password</label>
		    <div class="controls">
			<input type="password" class="input-xlarge" id="password" name="password" autocomplete="off">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="password2">Repeat Password</label>
		    <div class="controls">
			<input type="password" class="input-xlarge" id="password2" name="password2" autocomplete="off">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="firstname">First Name</label>
		    <div class="controls">
			<input type="text" class="input-xlarge" id="firstname" name="firstname" value="<?php echo $this->firstname; ?>">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="lastname">Last Name</label>
		    <div class="controls">
			<input type="text" class="input-xlarge" id="lastname" name="lastname" value="<?php echo $this->lastname; ?>">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="email">E-Mail</label>
		    <div class="controls">
			<input type="text" class="input-xlarge" id="email" name="email" value="<?php echo $this->email; ?>">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="language">Language</label>
		    <div class="controls">
			<input type="text" class="input-xlarge" id="language" name="language" value="<?php echo $this->language; ?>">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="timezone">Timezone</label>
		    <div class="controls">
			<input type="text" class="input-xlarge" id="timezone" name="timezone" value="<?php echo $this->timezone; ?>">
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="active">Active</label>
		    <div class="controls">
			<select name="active" id="active">
			    <option>Yes</option>
			    <option>No</option>
			</select>
		    </div>
		</div>
	    </div>
	    <div class="tab-pane" id="tab-member">
	    </div>
	    <div class="tab-pane" id="tab-permission">
	    </div>
	</div>

    </div>

    <div class="form-actions">
	<button class="btn btn-primary" type="submit" name="button" value="save">Save</button>
	<button class="btn" type="submit" name="button" value="save_and_close">Save and Close</button>
	<button class="btn btn-danger" type="submit" name="button" value="close">Close</button>
    </div>
</form>