<div class="page-header">
    <h2>Users</h2>
</div>

<div class="form-actions">
    <a class="btn btn-primary" href="index.php?action=adduser">New User</a>
</div>
<table class="table table-striped table-bordered table-condensed">
    <thead>
	<tr>
	    <th>#</th>
	    <th>name</th>
	    <th>group</th>
	    <th>rights</th>
	    <th>admin</th>
	    <th>rights editable</th>
	    <th>active</th>
	    <th>action</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach($this->users as $value) { ?>
	<tr>
	    <td><?php echo $value['id']; ?></td>
	    <td><?php echo $value['name']; ?></td>
	    <td><?php echo $this->groups[$value['defaultgroup']]['name']; ?></td>
	    <td><?php echo $value['defaultrights']; ?></td>
	    <td><?php echo (($value['admin'] == 1) ? 'yes':'no'); ?></td>
	    <td><?php echo (($value['rightedit'] == 1) ? 'yes':'no'); ?></td>
	    <td><?php echo (($value['enabled'] == 1) ? 'yes':'no'); ?></td>
	    <td>
		<a class="btn" href="index.php?action=edituser&uid=<?php echo $value['id']; ?>">edit</a>
		<a class="btn btn-danger" onclick="if(!confirm('Do you really want to delete this user?')) return false;" href="index.php?action=deluser&uid=<?php echo $value['id']; ?>">delete</a>
	    </td>
	</tr>
	<?php } ?>
    </tbody>
</table>