<!-- page navi -->
<div class="nav  navbar-default" style="margin-bottom:20px;">
    <ul class="nav nav-pills">
	<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'new')) { ?><li><a href="page/new/<?php echo $this->id; ?>"><?= $this->translate('add new page') ?></a></li><?php } ?>
	<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'edit')) { ?><li><a href="page/edit/<?php echo $this->id; ?>"><?= $this->translate('edit page') ?></a></li><?php } ?>
	<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'edit')) { ?><li><a href="javascript:;" onclick="window.open('page/move/<?php echo $this->id; ?>','Knowledgeroot','width=400,height=500,menubar=yes,resizable=yes,scrollbars=yes');"><?= $this->translate('move page') ?></a></li><?php } ?>
	<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'delete')) { ?><li><a href="javascript:;" onclick="if(confirm('<?= $this->translate('Do you really want to delete this page?') ?>')) { location.href='page/delete/<?php echo $this->id; ?>'; } else { return false; }"><?= $this->translate('delete page') ?></a></li><?php } ?>
	<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'new_content')) { ?><li><a href="content/new/<?php echo $this->id; ?>"><?= $this->translate('add new content') ?></a></li><?php } ?>
    </ul>
</div>

<div class="page-header">
    <h1 style="color: #797979"><?= $this->title ?>
    <?php if(!empty($this->subtitle)) { ?><small><?= $this->subtitle ?></small><?php } ?>
    </h1>
</div>
<?php if($this->showpagedescription || $this->showtableofcontent) { ?>
<div class="container-fluid">
<div class="row">
<!-- page description -->
    <?php if($this->showpagedescription) { ?>
    <div class="<?php if($this->showpagedescription) echo "col-md-8"; else echo "col-md-12"; ?>">
	<?= $this->description ?>
    </div>
    <?php } ?>

<!-- table of contents -->
    <?php if($this->showtableofcontent) { ?>
    <div class="well <?php if($this->showpagedescription) echo "col-md-4"; else echo "col-md-12"; ?> pull-right">
	<h2><?= $this->translate('contents') ?></h2>
	<ol>
    <?php
    foreach ($this->contents as $content) { // run for each content
	?>
	    <li><a href="#content<?php echo $content->getId(); ?>"><?= $content->getName() ?></a></li>
	<?php
    } // foreach end
    ?>
	</ol>
    </div>
    <?php } ?>
</div>
</div>
<?php } ?>
<!-- contents -->
<?php
foreach ($this->contents as $content) { // run for each content
    ?>
    <!-- anchor --><a name="content<?php echo $content->getId(); ?>"></a>
    <div class="panel-group" id="accordion<?php echo $content->getId(); ?>"><!-- start accordian -->
        <div class="panel panel-default">
    	<div class="panel-heading" style="background-color: #F6F6F6; cursor: pointer;">

    	    <h5 style="color: #428bca; margin: 0px 0px 0px 0px;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion<?php echo $content->getId(); ?>" href="#collapse<?php echo $content->getId(); ?>">
    		<?php echo $content->getName(); ?>
    	    </h5>

    	</div>
    	<div id="collapse<?php echo $content->getId(); ?>" class="panel-collapse collapse<?php if ($this->open || $this->contentcollapse) echo ' in'; ?>">

    	    <div class="panel-body" style="background-color:#ffffff;">
    		<div class="btn-toolbar">
    		    <div class="btn-group">
			<?php if(Knowledgeroot_Acl::iAmAllowed('content_' . $content->getId(), 'edit')) { ?><a class="btn btn-default" href="content/edit/<?php echo $content->getId(); ?>"><?= $this->translate('edit') ?></a><?php } ?>
    			<?php if(Knowledgeroot_Acl::iAmAllowed('content_' . $content->getId(), 'delete')) { ?><a class="btn btn-default" href="javascript:;" onclick="if(confirm('<?= $this->translate('Do you really want to delete?') ?>')) { location.href='content/delete/<?php echo $content->getId(); ?>'; } else { return false; }"><?= $this->translate('delete') ?></a><?php } ?>
    			<?php if(Knowledgeroot_Acl::iAmAllowed('content_' . $content->getId(), 'edit')) { ?><a class="btn btn-default" href="javascript:;" onclick="window.open('content/move/<?php echo $content->getId(); ?>','Knowledgeroot','width=400,height=500,menubar=yes,resizable=yes,scrollbars=yes');"><?= $this->translate('move') ?></a><?php } ?>
    			<?php if(Knowledgeroot_Acl::iAmAllowed('content_' . $content->getId(), 'edit')) { ?><a class="btn btn-default" href="javascript:;" onclick="window.open('print/<?php echo $content->getId(); ?>','Knowledgeroot','width=640,height=480,menubar=yes,resizable=yes,scrollbars=yes');"><?= $this->translate('print') ?></a><?php } ?>
			<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $content->getParent(), 'edit')) { ?><a class="btn btn-default" href="content/moveup/<?php echo $content->getId(); ?>"><i class="fa fa-arrow-up"></i></a><?php } ?>
			<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $content->getParent(), 'edit')) { ?><a class="btn btn-default" href="content/movedown/<?php echo $content->getId(); ?>"><i class="fa fa-arrow-down"></i></a><?php } ?>
    		    </div>
    		    <div class="btn-group pull-right">
    			<a class="btn btn-default pull-right" href="#top"><?= $this->translate('Top') ?></a>
    		    </div>
    		</div>
    		<br>
		    <?php echo $content->getContent(); ?>
		<br>
		<?php
		    if(is_array($this->files) && is_array($this->files[$content->getId()]) && count($this->files[$content->getId()]) > 0) {
			echo "<legend>" . $this->translate('Files') . "</legend><ul class=\"list-unstyled\">\n";
			foreach($this->files[$content->getId()] as $file) {
			    echo '<li>';
			    // need delete rights on content to delete a file
			    if(Knowledgeroot_Acl::iAmAllowed('content_' . $content->getId(), 'delete')) { echo '<a href="javascript:;" onclick="if(confirm(\'' . $this->translate('Do you really want to delete?') . '\')) { location.href=\'file/delete/'.$file->getId().'\'; }"><i class="fa fa-trash"></i></a> '; }
			    echo '<a href="./download/'.$file->getId().'/'.$file->getName().'"><i class="fa fa-download-alt" style="margin-right:5px;"></i> ' . $file->getName() . "</a>\n";
			    echo'
<a href="javascript:;" class="label label-info" rel="popover" data-html="true" data-placement="right" data-content="Size: '.$file->getSize().'<br>' . $this->translate('Downloads') . ':'.$file->getDownloads().'<br>' . $this->translate('MD5 Sum') . ':'.$file->getHash().'<br>' . $this->translate('changed') . ':'.$file->getChangeDate().'<br>' . $this->translate('changed by') . ':'.$file->getChangedBy().'<br>' . $this->translate('created') . ':'.$file->getCreateDate().'<br>' . $this->translate('created by') . ':'.$file->getCreatedBy().'" title="' . $this->translate('File Information') . '">info</a>
';
			    echo '</li>';
			}
			echo "</ul>";
		    }
		?>
		<?php if(Knowledgeroot_Acl::iAmAllowed('content_' . $content->getId(), 'edit')) { ?>
		<form>
		    <a onclick="selectContent('<?= $content->getId() ?>', '<?= $content->getName() ?>'); $('#fileUpload').modal('show');" href="javascript:;" class="btn btn-primary btn-mini"><i class="fa fa-plus icon-white" style="margin-right:2px;"></i><?= $this->translate('add') ?></a>
		</form>
		<?php } ?>
    	    </div>
    	    <div class="panel-footer"><?= $this->translate('Last change') ?>: <?= $content->getChangedBy()->getLogin() ?> - <?= $content->getChangeDate()->getUserDate() ?></div>
    	</div>
        </div>
    </div><!-- end accordian -->
    <?php
} // foreach end
?>
<script>
	$('[rel=popover]').popover();
</script>