<h1><i class="icon-key"></i> <?= $this->translate('Permissions') ?></h1>
<hr>

<div class="panel-group" id="accordion1"><!-- start accordian -->
    <div class="panel panel-default">
	<div class="panel-heading" style="background-color: #F6F6F6; border-left: 3px solid #1171A3;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse1"><?= $this->translate('Manage Users') ?></a>
	</div>
	<div id="collapse1" class="panel-collapse collapse">
	    <div class="panel-body">
		<?php echo $this->permissionPanel('manageUsers', array('new','edit','delete','show'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->

<div class="panel-group" id="accordion2"><!-- start accordian -->
    <div class="panel panel-default">
	<div class="panel-heading" style="background-color: #F6F6F6; border-left: 3px solid #52B9E9;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse2"><?= $this->translate('Manage Groups') ?></a>
	</div>
	<div id="collapse2" class="panel-collapse collapse">
	    <div class="panel-body">
		<?php echo $this->permissionPanel('manageGroups', array('new','edit','delete','show'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->

<div class="panel-group" id="accordion3"><!-- start accordian -->
    <div class="panel panel-default">
	<div class="panel-heading" style="background-color: #F6F6F6; border-left: 3px solid #FA3031;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion3" href="#collapse3"><?= $this->translate('Manage System Permissions') ?></a>
	</div>
	<div id="collapse3" class="panel-collapse collapse">
	    <div class="panel-body">
		<?php echo $this->permissionPanel('manageSystemPermissions', array('new','edit','delete','show'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->

<div class="panel-group" id="accordion4"><!-- start accordian -->
    <div class="panel panel-default">
	<div class="panel-heading" style="background-color: #F6F6F6; border-left: 3px solid #F88529;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion4" href="#collapse4"><?= $this->translate('Root Pages') ?></a>
	</div>
	<div id="collapse4" class="panel-collapse collapse">
	    <div class="panel-body">
		<?php echo $this->permissionPanel('manageRootPages', array('new'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->
