<h1>Permissions</h1>
<hr>

<div class="accordion" id="accordion1"><!-- start accordian -->
    <div class="accordion-group">
	<div class="accordion-heading" style="background-color: #F6F6F6;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse1">Manage Users</a>
	</div>
	<div id="collapse1" class="accordion-body collapse">
	    <div class="accordion-inner">
		<?php echo $this->permissionPanel('manageUsers', array('new','edit','delete','show'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->

<div class="accordion" id="accordion2"><!-- start accordian -->
    <div class="accordion-group">
	<div class="accordion-heading" style="background-color: #F6F6F6;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse2">Manage Groups</a>
	</div>
	<div id="collapse2" class="accordion-body collapse">
	    <div class="accordion-inner">
		<?php echo $this->permissionPanel('manageGroups', array('new','edit','delete','show'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->

<div class="accordion" id="accordion3"><!-- start accordian -->
    <div class="accordion-group">
	<div class="accordion-heading" style="background-color: #F6F6F6;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion3" href="#collapse3">Manage System Permissions</a>
	</div>
	<div id="collapse3" class="accordion-body collapse">
	    <div class="accordion-inner">
		<?php echo $this->permissionPanel('manageSystemPermissions', array('new','edit','delete','show'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->

<div class="accordion" id="accordion4"><!-- start accordian -->
    <div class="accordion-group">
	<div class="accordion-heading" style="background-color: #F6F6F6;">
	    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion4" href="#collapse4">Root Pages</a>
	</div>
	<div id="collapse4" class="accordion-body collapse">
	    <div class="accordion-inner">
		<?php echo $this->permissionPanel('manageRootPages', array('new','edit','delete','show'), array('show_save_button' => true)); ?>
	    </div>
	</div>
    </div>
</div><!-- end accordian -->