<div class="page-header">
    <h2><i class="icon-cog"></i> <?= $this->translate('Change Options') ?></h2>
</div>
<form class="form-horizontal" method="post">
    <input type="hidden" name="action" value="options" />
    <div class="control-group">
	<label class="control-label" for="login"><?= $this->translate('Login') ?></label>
	<div class="controls">
	    <input type="text" class="input-xlarge" id="login" name="login" disabled="disabled" value="<?= $this->login ?>">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="firstname"><?= $this->translate('First Name') ?></label>
	<div class="controls">
	    <input type="text" class="input-xlarge" id="firstname" name="first_name" value="<?= $this->first_name ?>">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="lastname"><?= $this->translate('Last Name') ?></label>
	<div class="controls">
	    <input type="text" class="input-xlarge" id="lastname" name="last_name" value="<?= $this->last_name ?>">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="email"><?= $this->translate('Email') ?></label>
	<div class="controls">
	    <input type="text" class="input-xlarge" id="email" name="email" value="<?= $this->email ?>">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="password"><?= $this->translate('Password') ?></label>
	<div class="controls">
	    <input type="password" class="input-xlarge" id="password" name="password">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="password1"><?= $this->translate('confirm Password') ?></label>
	<div class="controls">
	    <input type="password" class="input-xlarge" id="password1" name="password1">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="language"><?= $this->translate('Language') ?></label>
	<div class="controls">
	    <select name="language" id="language">
		<?php
		    foreach ($this->translations as $key => $value) {
			    // show translation name
			    echo '<option value="'.$key.'"'.(($this->language == $key) ? ' selected="selected"': '').'>' . $this->translate('[TRANSLATION_NAME]', $key) . '</option>';
		    }
		?>
	    </select>
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="timezone"><?= $this->translate('Timezone') ?></label>
	<div class="controls">
	    <select name="timezone" id="timezone">
		<?php
		    foreach($this->timezones as $key => $value) {
			echo '<option value="'.$key.'"'.(($this->timezone == $key) ? ' selected="selected"': '').'>'.$value."</option>\n";
		    }
		?>
	    </select>
	</div>
    </div>

    <div class="form-actions">
	<input class="btn btn-primary" type="submit" name="loginbutton" value="<?= $this->translate('Save') ?>" />
    </div>
</form>