
<div class="page-header">
    <h2>Optionen ändern</h2>
</div>
<form class="form-horizontal" action="index.php" method="post" name="formoptions" autocomplete="off">
    <input type="hidden" name="action" value="options" />
    <div class="control-group">
	<label class="control-label" for="password">Password</label>
	<div class="controls">
	    <input type="text" class="input-xlarge" id="password" name="password">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="password1">confirm Password</label>
	<div class="controls">
	    <input type="password" class="input-xlarge" id="password1" name="password1">
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="theme">Thema</label>
	<div class="controls">
	    <select name="theme" id="theme">
		<?php
		    foreach($this->themes as $value) {
			echo '<option value="'.$value['key'].'"'.(($_SESSION['theme'] == $value['key']) ? ' selected="selected"': '').'>'.$value['name'].'</option>';
		    }
		?>
	    </select>
	</div>
    </div>

    <div class="control-group">
	<label class="control-label" for="language">Sprache</label>
	<div class="controls">
	    <select name="language" id="language">
		<?php
		    foreach($this->languages as $value) {
			echo '<option value="'.$value['key'].'"'.(($_SESSION['language'] == $value['key']) ? ' selected="selected"': '').'>'.$value['name'].'</option>';
		    }
		?>
	    </select>
	</div>
    </div>

    <div class="form-actions">
	<input class="btn btn-primary" type="submit" name="loginbutton" value="speichern" />
    </div>
</form>
<?php
//print_r($this->themes);
//print_r($this->languages);
?>