<div class="page-header">
    <h2>
	<?php
	    if($this->action == 'new')
		echo $this->translate('Create Page');
	    else
		echo $this->translate('Edit Page');
	?>
    </h2>
</div>
<form class="form-horizontal" method="post">
    <div class="tabbable">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#tab-page"><?= $this->translate('Page') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-content"><?= $this->translate('Content') ?></a></li>
	    <?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'permission') || ($this->action == 'new' && Knowledgeroot_Acl::iAmAllowed('manageRootPages', 'new'))) { ?>
	    <li><a data-toggle="tab" href="#tab-permission"><?= $this->translate('Permissions') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-inherit-permission"><?= $this->translate('Inherit Permissions') ?></a></li>
	    <?php } ?>
	    <?php if($this->action != 'new') { ?><li><a data-toggle="tab" href="#tab-info"><?= $this->translate('Information') ?></a></li><?php } ?>
	    <?php if($this->action != 'new') { ?><li><a data-toggle="tab" href="#tab-history"><?= $this->translate('History') ?></a></li><?php } ?>
	</ul>
	<div class="tab-content">
	    <div class="tab-pane active" id="tab-page">
		<fieldset>
		    <div class="form-group">
			<label class="control-label col-sm-2" for="content-title"><?= $this->translate('Parent Page') ?></label>
			<div class="col-sm-4">
			    <input type="text" placeholder="<?= $this->translate('select a page') ?>" disabled="true" class="form-control" id="page-parent-name" size="255" name="page_parent_name" value="<?= $this->parentname ?>">
			    <p class="help-block">
				<?= $this->translate('Select a parent page') ?>
			    </p>
			    <input type="hidden" id="page-parent" size="255" name="page_parent" value="<?= $this->parent ?>">&nbsp;
			</div>
			<div class="col-sm-2">
			    <input type="button" class="btn btn-success" value="<?= $this->translate('select page') ?>" onclick="window.open('page/select','Knowledgeroot','width=400,height=500,menubar=yes,resizable=yes,scrollbars=yes');" />
			</div>
		    </div>

		    <div class="form-group">
			<label class="control-label col-sm-2" for="page-name"><?= $this->translate('Name') ?></label>
			<div class="col-sm-4">
			    <input type="text" class="form-control" id="page-name" name="page_title" size="255" value="<?= $this->title ?>">
			    <p class="help-block">
				<?= $this->translate('Name of Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="form-group">
			<label class="control-label col-sm-2" for="page-subtitle"><?= $this->translate('Subtitle') ?></label>
			<div class="col-sm-4">
			    <input type="text" class="form-control" id="page-subtitle" name="page_subtitle" size="255" value="<?= $this->subtitle ?>">
			    <p class="help-block">
				<?= $this->translate('Subtitle of Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="form-group">
			<label class="control-label col-sm-2" for="page-alias"><?= $this->translate('Alias') ?></label>
			<div class="col-sm-4">
			    <input type="text" class="form-control" id="page-alias" name="alias" size="255" value="<?= $this->alias ?>">
			    <p class="help-block">
				<?= $this->translate('Alias for Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="form-group">
			<label class="control-label col-sm-2" for="page-tooltip"><?= $this->translate('Tooltip') ?></label>
			<div class="col-sm-4">
			    <input type="text" class="form-control" id="page-tooltip" name="tooltip" value="<?= $this->tooltip ?>">
			    <p class="help-block">
				<?= $this->translate('Tooltip for Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="form-group">
			<label class="control-label col-sm-2" for="content-icon">Icon</label>
			<div class="col-sm-4">
			    <input type="text" class="form-control" id="content-icon" size="255" value="<?= $this->icon ?>">
			    <p class="help-block">
				Icon for Tree
			    </p>
			</div>
		    </div>

		    <div class="form-group">
			<label class="control-label col-sm-2" for="content-symlink"><?= $this->translate('Symlink') ?></label>
			<div class="col-sm-4">
			    <input type="text" class="form-control" id="content-symlink" size="255" value="<?= $this->symlink ?>">
			    <p class="help-block">
				<?= $this->translate('Symlink to other page') ?>
			    </p>
			</div>
		    </div>
		</fieldset>
	    </div>
	    <div class="tab-pane" id="tab-content">
		<div class="form-group">
		    <label class="control-label col-sm-2" for="content-title"><?= $this->translate('Position for new Content') ?>:</label>
		    <div class="col-sm-4">
			<select name="contentposition" class="form-control">
			    <option value="start" <?php if($this->contentposition == 'start') echo "selected=\"selected\""; ?>><?= $this->translate('at beginning') ?></option>
			    <option value="end" <?php if($this->contentposition == 'end') echo "selected=\"selected\""; ?>><?= $this->translate('at the end') ?></option>
			</select>
			<p class="help-block">
			    <?= $this->translate('Page') ?>
			</p>
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="optionsCheckboxList"><?= $this->translate('Options') ?>:</label>
		    <div class="col-sm-4">
			<label class="checkbox">
			    <input type="checkbox" <?php if($this->contentcollapse) echo "checked=\"checked\" "; ?>name="contentcollapse" value="1" />
			    <?= $this->translate('Show content collapsed') ?>
			</label>

			<label class="checkbox">
			    <input type="checkbox" <?php if($this->showpagedescription) echo "checked=\"checked\" "; ?>name="showpagedescription" value="1" />
			    <?= $this->translate('Show page description') ?>
			</label>

			<label class="checkbox">
			    <input type="checkbox" <?php if($this->showtableofcontent) echo "checked=\"checked\" "; ?>name="showtableofcontent" value="1" />
			    <?= $this->translate('Show table of content') ?>
			</label>

			<p class="help-block"><strong><?= $this->translate('Note') ?>:</strong> <?= $this->translate('Set options for the page') ?></p>

		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="page-description-editor"><?= $this->translate('Page description') ?></label>
		    <div class="col-sm-4">
			<?php
			echo $this->editor;
			?>
		    </div>
		</div>
	    </div>
	    <div class="tab-pane" id="tab-permission">
		<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'permission') || ($this->action == 'new' && Knowledgeroot_Acl::iAmAllowed('manageRootPages', 'new'))) { ?>
		<?php echo $this->permissionPanel('page_'.$this->id, array('new','edit','delete','show','new_content','permission'), array('show_save_button' => false, 'add_acl_on_form_submit' => true, 'add_user_permissions' => true)); ?>
		<?php } ?>
	    </div>
	    <div class="tab-pane" id="tab-inherit-permission">
		<div class="form-group">
		    <label class="control-label col-sm-2" for="optionsCheckboxList"><?= $this->translate('Options') ?>:</label>
		    <div class="col-sm-4">
			<label class="checkbox">
			    <input type="checkbox" name="subinheritrights" value="1" />
			    <?= $this->translate('enable inherit rights for subpages and contents') ?>
			</label>

			<label class="checkbox">
			    <input type="checkbox" name="subinheritrightseditable" value="1" />
			    <?= $this->translate('enable edit of rights for these pages and contents') ?>
			</label>
			<label class="checkbox">
			    <input type="checkbox" name="subinheritrightsdisable" value="1" />
			    <?= $this->translate('disable inherit rights for subpages and contents') ?>
			</label>
			<p class="help-block"><strong><?= $this->translate('Note') ?>:</strong> Foo Bar Hello World.</p>

		    </div>
		</div>

	    </div>
	    <?php if($this->action != 'new') { ?>
	    <div class="tab-pane" id="tab-info">
		<div class="form-group">
		    <label class="control-label col-sm-2" for="content-title"><?= $this->translate('Created By') ?></label>
		    <div class="col-sm-4">
			<span class="form-control uneditable-input"><?= $this->created_by ?></span>
			<p class="help-block">
			    <?= $this->translate('Username') ?>
			</p>
		    </div>
		</div>
		<div class="form-group">
		    <label class="control-label col-sm-2" for="content-title"><?= $this->translate('Created at') ?></label>
		    <div class="col-sm-4">
			<span class="form-control uneditable-input"><?= $this->create_date ?></span>
			<p class="help-block">
			    <?= $this->translate('creation date') ?>
			</p>
		    </div>
		</div>
	    </div>
	    <?php } ?>
	    <?php if($this->action != 'new') { ?>
	    <div class="tab-pane" id="tab-history">
		<script>
		    function restorePageDialog(restoreUrl) {
			bootbox.dialog({
			    message: "<?= $this->translate('Do you really want to restore this version?') ?>",
			    title: "<?= $this->translate('Page restore') ?>",
			    buttons: {
				cancel: {
				    label: "<?= $this->translate('cancel') ?>",
				    className: "btn-default"
				},
				ok: {
				    label: "<?= $this->translate('yes') ?>",
				    className: "btn-primary",
				    callback: function() {
					window.location.href = restoreUrl;
				    }
				}
			    }
			    });
		    }
		</script>
		<table class="table table-striped table-bordered table-hover">
		    <tr>
			<th><?= $this->translate('Version') ?></th>
			<th><?= $this->translate('User') ?></th>
			<th><?= $this->translate('Date') ?></th>
			<th><?= $this->translate('Action') ?></th>
		    </tr>
		<?php
		    foreach($this->versions as $key => $value) {
			?>
		    <tr>
			<td><span class="badge badge-info"><?= $value['version'] ?></span></td>
			<td><?= $value['user']->getLogin() ?></td>
			<td><?= $value['date']->getUserDate() ?></td>
			<td>
			    <a href="javascript:;" onclick="window.open('page/show/<?= $this->id ?>/version/<?= $value['version'] ?>','Knowledgeroot','width=550,height=400,menubar=yes,resizable=yes,scrollbars=yes');" class="btn btn-primary btn-small"><?= $this->translate('show') ?></a>
			    <a href="javascript:;" onclick="restorePageDialog('page/restore/<?= $this->id ?>/version/<?= $value['version'] ?>');" class="btn btn-primary btn-small"><?= $this->translate('restore') ?></a>
			</td>
		    </tr>
			<?php
		    }
		?>
		</table>
	    </div>
	    <?php } ?>
	</div>
    </div>
    <div class="row-fluid" style="margin-top: 20px;">
	<button class="btn btn-primary" type="submit" name="button" value="save"><?= $this->translate('Save') ?></button>&nbsp;
	<button class="btn btn-default" type="submit" name="button" value="save_and_close"><?= $this->translate('Save and Close') ?></button>&nbsp;
	<button class="btn btn-danger" type="submit" name="button" value="close"><?= $this->translate('Close') ?></button>&nbsp;
    </div>
</form>

<script>
    function selectPage(id, name) {
	$('#page-parent').val(id);
	$('#page-parent-name').val(name);
    }
</script>