<div class="page-header">
    <h2>
	<?php
	    if($this->action == 'new')
		echo $this->translate('Create Page');
	    else
		echo $this->translate('Edit Page');
	?>
    </h2>
</div>
<form class="form-horizontal" method="post">
    <div class="tabbable">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#tab-page"><?= $this->translate('Page') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-content"><?= $this->translate('Content') ?></a></li>
	    <?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'permission') || ($this->action == 'new' && Knowledgeroot_Acl::iAmAllowed('manageRootPages', 'new'))) { ?>
	    <li><a data-toggle="tab" href="#tab-permission"><?= $this->translate('Permissions') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-inherit-permission"><?= $this->translate('Inherit Permissions') ?></a></li>
	    <?php } ?>
	    <li><a data-toggle="tab" href="#tab-info"><?= $this->translate('Information') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-history"><?= $this->translate('History') ?></a></li>
	</ul>
	<div class="tab-content">
	    <div class="tab-pane active" id="tab-page">
		<fieldset>
		    <div class="control-group">
			<label class="control-label" for="content-title"><?= $this->translate('Page') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span2" id="content-title" size="255" name="page_parent" value="<?= $this->parent ?>">
			    <p class="help-block">
				<?= $this->translate('Parent Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="page-name"><?= $this->translate('Name') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="page-name" name="page_title" size="255" value="<?= $this->title ?>">
			    <p class="help-block">
				<?= $this->translate('Name of Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="page-subtitle"><?= $this->translate('Subtitle') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="page-subtitle" name="page_subtitle" size="255" value="<?= $this->subtitle ?>">
			    <p class="help-block">
				<?= $this->translate('Subtitle of Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="page-alias"><?= $this->translate('Alias') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="page-alias" name="page_alias" size="255" value="<?= $this->alias ?>">
			    <p class="help-block">
				<?= $this->translate('Alias for Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="page-tooltip"><?= $this->translate('Tooltip') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="page-tooltip" name="tooltip" value="<?= $this->tooltip ?>">
			    <p class="help-block">
				<?= $this->translate('Tooltip for Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="content-icon">Icon</label>
			<div class="controls">
			    <input type="text" class="input-xlarge span2" id="content-icon" size="255" value="<?= $this->icon ?>">
			    <p class="help-block">
				Icon for Tree
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="content-symlink"><?= $this->translate('Symlink') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span2" id="content-symlink" size="255" value="<?= $this->symlink ?>">
			    <p class="help-block">
				<?= $this->translate('Symlink to other page') ?>
			    </p>
			</div>
		    </div>
		</fieldset>
	    </div>
	    <div class="tab-pane" id="tab-content">
		<div class="control-group">
		    <label class="control-label" for="content-title"><?= $this->translate('Position for new Content') ?>:</label>
		    <div class="controls">
			<select name="contentposition">
			    <option value="start" <?php if($this->contentposition == 'start') echo "selected=\"selected\""; ?>><?= $this->translate('at beginning') ?></option>
			    <option value="end" <?php if($this->contentposition == 'end') echo "selected=\"selected\""; ?>><?= $this->translate('at the end') ?></option>
			</select>
			<p class="help-block">
			    <?= $this->translate('Page') ?>
			</p>
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="optionsCheckboxList"><?= $this->translate('Options') ?>:</label>
		    <div class="controls">
			<label class="checkbox">
			    <input type="checkbox" <?php if($this->contentcollapse) echo "checked=\"checked\" "; ?>name="contentcollapse" value="1" />
			    <?= $this->translate('Show content collapsed') ?>
			</label>

			<label class="checkbox">
			    <input type="checkbox" <?php if($this->showpagedescription) echo "checked=\"checked\" "; ?>name="showpagedescription" value="1" />
			    <?= $this->translate('Show page description') ?>
			</label>

			<label class="checkbox">
			    <input type="checkbox" <?php if($this->showtableofcontent) echo "checked=\"checked\" "; ?>name="showtableofcontent" value="1" />
			    <?= $this->translate('Show table of content') ?>
			</label>

			<p class="help-block"><strong><?= $this->translate('Note') ?>:</strong> <?= $this->translate('Set options for the page') ?></p>

		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="page-description-editor"><?= $this->translate('Page description') ?></label>
		    <div class="controls">
			<?php
			echo $this->editor;
			?>
		    </div>
		</div>
	    </div>
	    <div class="tab-pane" id="tab-permission">
		<?php if(Knowledgeroot_Acl::iAmAllowed('page_' . $this->id, 'permission') || ($this->action == 'new' && Knowledgeroot_Acl::iAmAllowed('manageRootPages', 'new'))) { ?>
		<?php echo $this->permissionPanel('page_'.$this->id, array('new','edit','delete','show','new_content','permission'), array('show_save_button' => false, 'add_acl_on_form_submit' => true, 'add_user_permissions' => true)); ?>
		<?php } ?>
	    </div>
	    <div class="tab-pane" id="tab-inherit-permission">
		<div class="control-group">
		    <label class="control-label" for="optionsCheckboxList"><?= $this->translate('Options') ?>:</label>
		    <div class="controls">
			<label class="checkbox">
			    <input type="checkbox" name="subinheritrights" value="1" />
			    <?= $this->translate('enable inherit rights for subpages and contents') ?>
			</label>

			<label class="checkbox">
			    <input type="checkbox" name="subinheritrightseditable" value="1" />
			    <?= $this->translate('enable edit of rights for these pages and contents') ?>
			</label>
			<label class="checkbox">
			    <input type="checkbox" name="subinheritrightsdisable" value="1" />
			    <?= $this->translate('disable inherit rights for subpages and contents') ?>
			</label>
			<p class="help-block"><strong><?= $this->translate('Note') ?>:</strong> Foo Bar Hello World.</p>

		    </div>
		</div>

	    </div>
	    <div class="tab-pane" id="tab-info">
		<div class="control-group">
		    <label class="control-label" for="content-title"><?= $this->translate('Created By') ?></label>
		    <div class="controls">
			<span class="input-xlarge uneditable-input">admin</span>
			<p class="help-block">
			    <?= $this->translate('Username') ?>
			</p>
		    </div>
		</div>
		<div class="control-group">
		    <label class="control-label" for="content-title"><?= $this->translate('Created at') ?></label>
		    <div class="controls">
			<span class="input-xlarge uneditable-input">20120606</span>
			<p class="help-block">
			    <?= $this->translate('creation date') ?>
			</p>
		    </div>
		</div>
	    </div>
	    <div class="tab-pane" id="tab-history">
	    </div>
	</div>
    </div>
    <div class="form-actions">
	<button class="btn btn-primary" type="submit" name="button" value="save"><?= $this->translate('Save') ?></button>&nbsp;
	<button class="btn" type="submit" name="button" value="save_and_close"><?= $this->translate('Save and Close') ?></button>&nbsp;
	<button class="btn btn-danger" type="submit" name="button" value="close"><?= $this->translate('Close') ?></button>&nbsp;
    </div>
</form>