<div class="page-header">
    <h2>
	<?php
	    if($this->action == 'new')
		echo $this->translate('Create Content');
	    else
		echo $this->translate('Edit Content');
	?>
    </h2>
</div>
<form class="form-horizontal" method="post">
    <div class="tabbable">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#tab-content"><?= $this->translate('Content') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-position"><?= $this->translate('Position') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-permission"><?= $this->translate('Permissions') ?></a></li>
	    <?php if($this->action != 'new') { ?><li><a data-toggle="tab" href="#tab-info"><?= $this->translate('Information') ?></a></li><?php } ?>
	    <?php if($this->action != 'new') { ?><li><a data-toggle="tab" href="#tab-history"><?= $this->translate('History') ?></a></li><?php } ?>
	</ul>
	<div class="tab-content">
	    <div class="tab-pane active" id="tab-content">
		<fieldset>
		    <div class="control-group">
			<label class="control-label" for="content-title"><?= $this->translate('Titel') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="content-title" name="content_title" value="<?= $this->title; ?>" size="255">
			    <p class="help-block">
				<?= $this->translate('Title of content') ?>
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="content-editor"><?= $this->translate('Content') ?></label>
			<div class="controls">
			    <?php
			    echo $this->editor;
			    ?>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="content-tags"><?= $this->translate('Tags') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span9" id="content-tags" name="content-tags" value="<?= $this->tags; ?>">
			    <p class="help-block">
				<?= $this->translate('Comma separated words') ?>
			    </p>
			</div>
		    </div>
		</fieldset>
	    </div>
	    <div class="tab-pane" id="tab-position">
		    <div class="control-group">
			<label class="control-label" for="content-page"><?= $this->translate('Page') ?></label>
			<div class="controls">
			    <input type="text" class="input-xlarge span2" id="content-page" name="content_page" value="<?= $this->page; ?>" size="255">
			    <p class="help-block">
				<?= $this->translate('Page') ?>
			    </p>
			</div>
		    </div>

		    <div class="control-group">
			<label class="control-label" for="position"><?= $this->translate('Position') ?></label>
			<div class="controls">
			    <select name="position" id="position">
				<?php
				if(is_array($this->positions)) {
				    foreach ($this->positions as $position) {
					echo '<option value="' . $position['key'] . '"' . (($position['default']) ? ' selected="selected"' : '') . '>&larr; ' . $position['title'] . '</option>';
				    }
				}
				?>
			    </select>
			    <p class="help-block">
				<?= $this->translate('Define position of content on page') ?>
			    </p>
			</div>
		    </div>
	    </div>
	    <div class="tab-pane" id="tab-permission">
		<?php echo $this->permissionPanel('content_'.$this->id, array('edit','delete','show','print','permission'), array('show_save_button' => false, 'add_acl_on_form_submit' => true)); ?>
	    </div>
	    <?php if($this->action != 'new') { ?>
	    <div class="tab-pane" id="tab-info">
		    <div class="control-group">
			<label class="control-label" for="content-title"><?= $this->translate('Created By') ?></label>
			<div class="controls">
			    <span class="input-xlarge uneditable-input"><?= $this->created_by ?></span>
			    <p class="help-block">
				<?= $this->translate('Username') ?>
			    </p>
			</div>
		    </div>
		    <div class="control-group">
			<label class="control-label" for="content-title"><?= $this->translate('Created at') ?></label>
			<div class="controls">
			    <span class="input-xlarge uneditable-input"><?= $this->create_date ?></span>
			    <p class="help-block">
				<?= $this->translate('creation date') ?>
			    </p>
			</div>
		    </div>
	    </div>
	    <?php } ?>
	    <?php if($this->action != 'new') { ?>
	    <div class="tab-pane" id="tab-history">
		<table class="table table-striped table-bordered table-hover">
		    <tr>
			<th><?= $this->translate('Version') ?></th>
			<th><?= $this->translate('User') ?></th>
			<th><?= $this->translate('Date') ?></th>
			<th><?= $this->translate('Action') ?></th>
		    </tr>
		<?php
		    foreach($this->versions as $key => $value) {
			?>
		    <tr>
			<td><span class="badge badge-info"><?= $value['version'] ?></span></td>
			<td><?= $value['user']->getLogin() ?></td>
			<td><?= $value['date']->getUserDate() ?></td>
			<td><a href="javascript:;" onclick="window.open('content/show/<?= $this->id ?>/version/<?= $value['version'] ?>','Knowledgeroot','width=550,height=400,menubar=yes,resizable=yes,scrollbars=yes');" class="btn btn-primary btn-small"><?= $this->translate('show') ?></a></td>
		    </tr>
			<?php
		    }
		?>
		</table>
	    </div>
	    <?php } ?>
	</div>
    </div>
    <div class="form-actions">
	<button class="btn btn-primary" type="submit" name="button" value="save"><?= $this->translate('Save') ?></button>&nbsp;
	<button class="btn" type="submit" name="button" value="save_and_close"><?= $this->translate('Save and Close') ?></button>&nbsp;
	<button class="btn btn-danger" type="submit" name="button" value="close"><?= $this->translate('Close') ?></button>&nbsp;
    </div>
</form>