<div style="padding: 5px;">
<h2><?= $this->translate('Move Content') ?></h2>
<?php if($this->target != '') { ?>
<script>
    window.opener.location.href = 'page/<?= $this->pageid ?>';
    window.close();
</script>
<button class="btn btn-primary" onclick="window.close();"><?= $this->translate('close') ?></button>
<?php } else { ?>
<div class="well">
	<div class="input-group">
		<div class="input-group-btn">
			<button class="btn btn-default" type="button" onclick="$('#treeOne').jstree(true).refresh();"><i class="fa fa-refresh"></i></button>
			<button class="btn btn-default" type="button" onclick="$('#treeOne').jstree('open_all');"><i class="fa fa-plus"></i></button>
			<button class="btn btn-default" type="button" onclick="$('#treeOne').jstree('close_all');"><i class="fa fa-minus"></i></button>
		</div>
		<input id="treeOneSearch" type="text" placeholder="<?= $this->translate('Search') ?>" class="form-control">
	</div>
	<script type="text/javascript">
	    $.getJSON( "./page/jsontree", function( data ) {
		    $(function () { $('#treeOne')
		    .on('changed.jstree', function (e, data) {
			item = data.node.original;
			location.href = 'content/move/<?= $this->contentid ?>/to/' + item.id;
		    })
		    .jstree({
			'core' : {
			    'data' : data.items
			},
			'sort': function(a, b) {
				return this.get_node(a).original.sort > this.get_node(b).original.sort ? 1 : -1;
			},
			"plugins" : [ "sort", "state", "search" ]
		    }); });

		var to = false;
		$('#treeOneSearch').keyup(function () {
			if(to)
				clearTimeout(to);

			to = setTimeout(function () {
				var v = $('#treeOneSearch').val();
				$('#treeOne').jstree(true).search(v);
			}, 250);
		});
	    });
	</script>

	<div id="treeOne"></div>
</div>

<button class="btn btn-primary pull-right" onclick="window.close();"><?= $this->translate('close') ?></button>
<?php } ?>
</div>