<div style="padding: 5px;">
<h2><?= $this->translate('Select Content') ?></h2>
<div class="row-fluid">
<div class="well">
    <div class="btn-group">
	<a class="btn btn-default" href="javascript:;" onclick="dijit.byId('treeOne').expandAll();"><i class="icon-plus"></i></a>
	<a class="btn btn-default" href="javascript:;" onclick="dijit.byId('treeOne').collapseAll();"><i class="icon-minus"></i></a>
    </div>
    <script type="text/javascript">
	require(["dojo/parser", "dojo/data/ItemFileReadStore", "dijit/Tree"], function() {

	    var store = new dojo.data.ItemFileReadStore({
		url: "./page/jsontree"
	    });

	    var treeModel = new dijit.tree.ForestStoreModel({
		store: store,
		query: {"type": "root"},
		rootId: "root",
		rootLabel: "Knowledgeroot",
		childrenAttrs: ["children"]
	    });

	    new dijit.Tree({
		model: treeModel,
		showRoot: false,
		persist: true,
		onClick: function(item){
		    // Get the URL from the item, and navigate to it
		    location.href = 'content/select/' + item.id;
		}
	    }, "treeOne");
	});
    </script>

    <div id="treeOne"></div>
</div>
<div class="span8">
<?php
	if(is_array($this->contents)) {
		echo '<ul class="nav nav-tabs nav-stacked">';
		foreach($this->contents as $key => $value) {
			echo "<li><a onclick=\"window.opener.selectContent('".$value->getId()."', '".$value->getName()."'); window.close();\" href=\"javascript:;\">" . $value->getName() . "</a></li>\n";
		}
		echo '</ul>';
	} else {
		echo $this->translate('Please select a page!');
	}
?>
</div>
</div>
<button class="btn btn-primary pull-right" onclick="window.close();"><?= $this->translate('close') ?></button>
</div>