<div class="page-header">
    <h2><i class="icon-user"></i> <?= $this->translate('Users') ?></h2>
</div>

<table id="users" class="tablesorter table table-striped table-bordered table-hover">
    <thead>
	<tr>
	    <th>#</th>
	    <th><?= $this->translate('firstname') ?></th>
	    <th><?= $this->translate('lastname') ?></th>
	    <th><?= $this->translate('login') ?></th>
	    <th><?= $this->translate('email') ?></th>
	    <th><?= $this->translate('language') ?></th>
	    <th><?= $this->translate('timezone') ?></th>
	    <th><?= $this->translate('active') ?></th>
	    <th><?= $this->translate('action') ?></th>
	</tr>
    </thead>
    <?php
    foreach ($this->users as $value) {
	?>
        <tr>
    	<td><?= $value->getId(); ?></td>
    	<td><?= $value->getFirstName(); ?></td>
    	<td><?= $value->getLastName(); ?></td>
    	<td><?= $value->getLogin(); ?></td>
    	<td><?= $value->getEmail(); ?></td>
    	<td><?= $value->getLanguage(); ?></td>
    	<td><?= $value->getTimezone(); ?></td>
    	<td><?= (($value->getActive()) ? 'Yes' : 'No'); ?></td>
    	<td>
    	    <div class="btn-group">
    		<a class="btn btn-primary" href="./user/edit/<?= $value->getId(); ?>"><?= $this->translate('edit') ?></a>
    		<button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
    		    <span class="caret"></span>
    		</button>
    		<ul class="dropdown-menu">
		    <!-- <li><a href="./user/sulogin/<?= $value->getId(); ?>"><?= $this->translate('SU-Login') ?></a></li> -->
		    <li><a href="./user/<?= (($value->getActive()) ? $this->translate('disable') : $this->translate('enable')); ?>/<?= $value->getId(); ?>"><?= (($value->getActive()) ? $this->translate('disable') : $this->translate('enable')); ?></a></li>
		    <li><a href="./user/delete/<?= $value->getId(); ?>"><?= $this->translate('delete') ?></a></li>
    		</ul>
    	    </div>
    	</td>
        </tr>

    <?php } ?>
</table>

<div class="form-actions">
    <a class="btn btn-primary" href="./user/new"><?= $this->translate('new User') ?></a>
</div>