<div class="page-header">
    <h2><i class="fa fa-user"></i>
	<?php
	if ($this->action == 'new')
	    echo $this->translate('Create User');
	else
	    echo $this->translate('Edit User');
	?>
    </h2>
</div>
<form class="form-horizontal" method="post">
    <div class="tabbable">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#tab-user"><?= $this->translate('User') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-member"><?= $this->translate('Member Of') ?></a></li>
	</ul>
	<div class="tab-content">
	    <div class="tab-pane active" id="tab-user">
		<div class="form-group">
		    <label class="control-label col-sm-2" for="login"><?= $this->translate('Login') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="login" name="login" value="<?php echo $this->login; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="password"><?= $this->translate('Password') ?></label>
		    <div class="col-sm-4">
			<input type="password" class="form-control" id="password" name="password" autocomplete="off">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="password2"><?= $this->translate('Repeat Password') ?></label>
		    <div class="col-sm-4">
			<input type="password" class="form-control" id="password2" name="password2" autocomplete="off">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="firstname"><?= $this->translate('First Name') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="firstname" name="firstname" value="<?php echo $this->firstname; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="lastname"><?= $this->translate('Last Name') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="lastname" name="lastname" value="<?php echo $this->lastname; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="email"><?= $this->translate('E-Mail') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="email" name="email" value="<?php echo $this->email; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="language"><?= $this->translate('Language') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="language" name="language" value="<?php echo $this->language; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="timezone">i<?= $this->translate('Timezone') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="timezone" name="timezone" value="<?php echo $this->timezone; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="active"><?= $this->translate('Active') ?></label>
		    <div class="col-sm-4">
			<select name="active" id="active" class="form-control">
			    <option value="1"<?= ((!is_null($this->active) && $this->active) ? ' selected="selected"' : '') ?>><?= $this->translate('Yes') ?></option>
			    <option value="0"<?= ((!is_null($this->active) && !$this->active) ? ' selected="selected"' : '') ?>><?= $this->translate('No') ?></option>
			</select>
		    </div>
		</div>
	    </div>
	    <div class="tab-pane" id="tab-member">
		<?php echo $this->memberPanel('user', new Knowledgeroot_User($this->id), array('show_users' => false)); ?>
	    </div>
	</div>

    </div>

    <div class="row-fluid" style="margin-top: 20px;">
	<button class="btn btn-primary" type="submit" name="button" value="save"><?= $this->translate('Save') ?></button>
	<button class="btn btn-default" type="submit" name="button" value="save_and_close"><?= $this->translate('Save and Close') ?></button>
	<button class="btn btn-danger" type="submit" name="button" value="close"><?= $this->translate('Close') ?></button>
    </div>
</form>