<div class="page-header">
    <h2><i class="fa fa-group"></i>
	<?php
	if ($this->action == 'new')
	    echo $this->translate('Create Group');
	else
	    echo $this->translate('Edit Group');
	?>
    </h2>
</div>
<form class="form-horizontal" method="post">
    <div class="tabbable">
	<ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#tab-group"><?= $this->translate('Group') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-member"><?= $this->translate('Member Of') ?></a></li>
	    <li><a data-toggle="tab" href="#tab-members"><?= $this->translate('Members') ?></a></li>
	</ul>
	<div class="tab-content">
	    <div class="tab-pane active" id="tab-group">
		<div class="form-group">
		    <label class="control-label col-sm-2" for="name"><?= $this->translate('Name') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="name" name="name" value="<?php echo $this->name; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="description"><?= $this->translate('Description') ?></label>
		    <div class="col-sm-4">
			<input type="text" class="form-control" id="description" name="description" value="<?php echo $this->description; ?>">
		    </div>
		</div>

		<div class="form-group">
		    <label class="control-label col-sm-2" for="active"><?= $this->translate('Active') ?></label>
		    <div class="col-sm-4">
			<select name="active" id="active" class="form-control">
			    <option value="1"<?= ((!is_null($this->active) && $this->active) ? ' selected="selected"' : '') ?>><?= $this->translate('Yes') ?></option>
			    <option value="0"<?= ((!is_null($this->active) && !$this->active) ? ' selected="selected"' : '') ?>><?= $this->translate('No') ?></option>
			</select>
		    </div>
		</div>
	    </div>
	    <div class="tab-pane" id="tab-member">
		<?php echo $this->memberPanel('group', new Knowledgeroot_Group($this->id), array('show_users' => false)); ?>
	    </div>
	    <div class="tab-pane" id="tab-members">
		<?php echo $this->memberPanel('member', new Knowledgeroot_Group($this->id), array('show_users' => true, 'show_members' => true)); ?>
	    </div>
	</div>

    </div>

    <div class="row-fluid" style="margin-top: 20px;">
	<button class="btn btn-primary" type="submit" name="button" value="save"><?= $this->translate('Save') ?></button>
	<button class="btn btn-default" type="submit" name="button" value="save_and_close"><?= $this->translate('Save and Close') ?></button>
	<button class="btn btn-danger" type="submit" name="button" value="close"><?= $this->translate('Close') ?></button>
    </div>
</form>