<div class="page-header">
    <h2><i class="icon-group"></i> <?= $this->translate('Groups') ?></h2>
</div>

<table id="groups" class="tablesorter table table-striped table-bordered table-hover">
    <thead>
	<tr>
	    <th>#</th>
	    <th><?= $this->translate('Name') ?></th>
	    <th><?= $this->translate('Description') ?></th>
	    <th><?= $this->translate('active') ?></th>
	    <th><?= $this->translate('action') ?></th>
	</tr>
    </thead>
    <?php
    foreach ($this->groups as $value) {
	?>
        <tr>
    	<td><?= $value->getId(); ?></td>
    	<td><?= $value->getName(); ?></td>
    	<td><?= $value->getDescription(); ?></td>
    	<td><?= (($value->getActive()) ? $this->translate('Yes') : $this->translate('No')); ?></td>
    	<td>
    	    <div class="btn-group">
    		<a class="btn btn-primary" href="./group/edit/<?= $value->getId(); ?>"><?= $this->translate('edit') ?></a>
    		<button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
    		    <span class="caret"></span>
    		</button>
    		<ul class="dropdown-menu">
		    <!-- <li><a href="./user/sulogin/<?= $value->getId(); ?>"><?= $this->translate('SU-Login') ?></a></li> -->
		    <li><a href="./group/<?= (($value->getActive()) ? $this->translate('disable') : $this->translate('enable')); ?>/<?= $value->getId(); ?>"><?= (($value->getActive()) ? $this->translate('disable') : $this->translate('enable')); ?></a></li>
		    <li><a href="./group/delete/<?= $value->getId(); ?>"><?= $this->translate('delete') ?></a></li>
    		</ul>
    	    </div>
    	</td>
        </tr>

    <?php } ?>
</table>

<div class="form-actions">
    <a class="btn btn-primary" href="./group/new"><?= $this->translate('new Group') ?></a>
</div>