<!-- stores -->
<script>
    var permissionStore_<?= $this->name ?> = <?php echo ((count($this->permissions) > 0) ? json_encode($this->permissions) : '{}'); ?>;
    var roleStore_<?= $this->name ?> = <?= json_encode($this->roles) ?>;
    var actionStore_<?= $this->name ?> = <?= json_encode($this->actions) ?>;
</script>

<!-- main permission panel -->
<div class="permission-panel" data-panel-name="<?= $this->name ?>">
    <button type="button" class="btn btn-default" data-toggle="modal" href="#permissionPanelRoles_<?= $this->name ?>"><?= $this->translate('add Role') ?></button>
    <button type="button" class="btn btn-default" data-panel-event="removeUser"><?= $this->translate('remove selected Role') ?></button>
    <div class="row">
	<div class="col-xs-6">
	    <h5><?= $this->translate('Group- or Username') ?>:</h5>
	    <div class="permission-panel-roles">
		<ul>
		    <?php foreach ($this->permissions as $key => $value) { ?>
    		    <li><a data-panel-name="<?= $this->name ?>" data-panel-userid="<?= $key ?>" href="javascript:;"><?= $value['name'] ?> (<?= $key[0] ?>)</a></li>
		    <?php } ?>
		</ul>
	    </div>
	</div>

	<div class="col-xs-6">
	    <h5><?= $this->translate('Permissions') ?>:</h5>
	    <div class="permission-panel-rights well well-small" data-panel-name="<?= $this->name ?>" style="display:none;">
		<?php
		foreach ($this->actions as $value) {
		    ?>
    		<div class="action" data-panel-action-name="<?= $value ?>">
    		    <span class="action-name"><?= $value ?>:</span>
    		    <div class="btn-group" data-toggle="buttons">
			<label class="btn btn-success btn-small">
				<input type="radio" name="<?= $this->name ?>" data-panel-name="<?= $this->name ?>" data-panel-action-name="<?= $value ?>" data-panel-action-right="allow"><?= $this->translate('allow') ?>
			</label>
			<label class="btn btn-danger btn-small">
				<input type="radio" name="<?= $this->name ?>" data-panel-name="<?= $this->name ?>" data-panel-action-name="<?= $value ?>" data-panel-action-right="deny"><?= $this->translate('deny') ?>
			</label>

    		    </div>
    		</div>
		<?php } ?>
	    </div>
	</div>
    </div>
    <?php if($this->showSaveButton) { ?>
    <div class="row-fluid">
	<div class="col-xs-12">
	    <button type="button" class="pull-right btn btn-primary permission-panel-save-button" data-panel-name="<?= $this->name ?>" data-panel-save-url="./permissions/save"><?= $this->translate('Save') ?></button>
	</div>
    </div>
    <?php } ?>
    <?php if($this->addAclOnFormSubmit) { ?>
    <input type="hidden" id="inputAcl<?= $this->name ?>" name="acl" value="" />
    <script>
	$(window).load(function() {
	    updateAclField('<?= $this->name ?>');
	});
    </script>
    <?php } ?>
    <?php if($this->addUserPermissions && count($this->permissions) == 0) { ?>
    <script>
	$(window).load(function() {
		addUserToList('<?= $this->name ?>', 'U_<?= $this->userId ?>');
	});
    </script>
    <?php } ?>
</div>

<!-- modal box with available roles -->
<div class="modal fade permissionPanelRoles" id="permissionPanelRoles_<?= $this->name ?>" data-panel-name="<?= $this->name ?>" tabindex="-1" role="dialog" aria-labelledby="permissionPanelRoles_<?= $this->name ?>_Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    <h3><?= $this->translate('Roles') ?></h3>
	</div>
	<div class="modal-body">
	    <h5><?= $this->translate('Select roles to add') ?>:</h5>
	    <select multiple="multiple">
		<?php foreach($this->roles as $key => $value) { ?>
		<option value="<?= $key ?>"><?= $value ?></option>
		<?php } ?>
	    </select>
	</div>
	<div class="modal-footer">
	    <button class="btn btn-primary" data-panel-event="addUser" type="button"><?= $this->translate('Add') ?></button>
	    <button class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
	</div>
    </div>
  </div>
</div>
